# docker-compose.yml
version: '3.8'

services:
  webserver:
    container_name: whatsapp-middleware
    build: .
    env_file:
      - .env
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
